[package]
name = "stabs"
version = "0.7.0" # regex urls
edition = "2021"

[dependencies]
rayon = "1.10.0"
regex = "1.11.1"
scraper = "0.21.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
ureq = "2.10.1"
